# --- Server Configuration ---
server.port=8088
spring.application.name=wallet-service

# --- Data Base Configuration (Postgres) ---

spring.datasource.url=jdbc:postgresql://localhost:5432/wallet_db
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Kafka Configuration  (docker) ---
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=wallet-group
# name of "Subject" discussion
application.kafka.topic.wallet-transaction=wallet-transaction-topic

# message format (send a text/JSON)
#translate for key : simple text
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#translate for value (msg) : json
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# show SQL in console
spring.jpa.show-sql=true
# Convert SQL for that it'is readable
spring.jpa.properties.hibernate.format_sql=true


