# --- Configuration Server ---
server.port=8082
spring.application.name=wallet-service

# --- Configuration Data Base(Postgres) ---

spring.datasource.url=jdbc:postgresql://localhost:5432/wallet_db
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Configuration Kafka ---
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=wallet-group
# name of "Subject" discussion
application.kafka.topic.wallet-transaction=wallet-transaction-topic

# message format (send a text/JSON)
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# show SQL in console
spring.jpa.show-sql=true
# Convert SQL for that it'is readable
spring.jpa.properties.hibernate.format_sql=true


